export const MyCourses = [
  {
    id: 1,
    name: "Course 1",
    lectures_count: 10,
    duration: "2 hours",
    level: "Beginner",
    rating: 4.5,
    students: 1000,
    price: 100,
    discount: 10,
    instructor: "John Doe",
    category: "Web Development",
    subcategory: "React",
    language: "English",
    last_updated: "2020-01-01",
    created_at: "2020-01-01",
    progress: 0.5,
    status: "In Progress",
    actions: {
      view: true,
      edit: true,
      delete: true,
    },
    enrolled: "2020-01-01",
    last_accessed: "2020-01-01",
  },
  {
    id: 1,
    name: "Course 1",
    lectures_count: 10,
    duration: "2 hours",
    level: "Beginner",
    rating: 4.5,
    students: 1000,
    price: 100,
    discount: 10,
    instructor: "John Doe",
    category: "Web Development",
    subcategory: "React",
    language: "English",
    last_updated: "2020-01-01",
    created_at: "2020-01-01",
    progress: 0.5,
    status: "In Progress",
    actions: {
      view: true,
      edit: true,
      delete: true,
    },
    enrolled: "2020-01-01",
    last_accessed: "2020-01-01",
  },
];
