export const NewCoursesData = [
  {
    path: "/app/new-courses",
    image: "https://i.imgur.com/4ZQZQ9M.png",
    description: {
      title: "New Courses",
      subtitle: "New Courses",
      text: "New Courses",
      rating: 4.5,
      current_price: "19.99",
      old_price: "29.99",
      discount: "33%",
      total_lectures: "10",
      total_hours: "2",
      total_students: "100",
      total_reviews: "10",
    },
  },
  {
    path: "/app/new-courses",
    image: "https://i.imgur.com/4ZQZQ9M.png",
    description: {
      title: "New Courses",
      subtitle: "New Courses",
      text: "New Courses",
      rating: "4",
      current_price: "19.99",
      old_price: "29.99",
      discount: "33%",
      total_lectures: "10",
      total_hours: "2",
      total_students: "100",
      total_reviews: "10",
    },
  },
  {
    path: "/app/new-courses",
    image: "https://i.imgur.com/4ZQZQ9M.png",
    description: {
      title: "New Courses",
      subtitle: "New Courses",
      text: "New Courses",
      rating: "4.5",
      total_reviews: "10",
      current_price: "19.99",
      old_price: "29.99",
      discount: "33%",
      total_lectures: "10",
      total_hours: "2",
      total_students: "100",
    },
  },
];
